### ISSUE TITLE
Add Edit and Delete Functionality for Insurance Transactions

### ISSUE THREAD

**Issue by Munashe-Njanji** [Grace-Rasaily780/boringfinance#7]
### Description
Need to implement basic edit and delete operations for  transactions. Users should be able to modify transaction details or remove transactions when needed.

### Features
- Edit transaction amount
- Edit transaction date
- Edit transaction category/type
- Delete transaction with confirmation

#### Edit Feature
```javascript
// Example endpoint structure
PUT /transaction/:id
{
    "amount": number,
    "date": string,
    "purpose": string,
    "group": string,
    "category": string,
    "user": User,
}
```

#### Delete Feature
```javascript
// Example endpoint
DELETE /transaction/:id
```

### Tasks
- [ ] Add edit button to transaction list
- [ ] Create edit form component
- [ ] Implement update API endpoint
- [ ] Add delete button with confirmation
- [ ] Implement delete API endpoint
- [ ] Add success/error notifications
- [ ] Update transaction list after edit/delete

### UI Requirements
1. Edit:
   - Simple edit button next to each transaction
   - Form with current values pre-filled
   - Save/Cancel buttons

2. Delete:
   - Delete button with confirmation dialog
   - Visual feedback after deletion

### Testing Checklist
- [ ] Edit saves correct values
- [ ] Delete removes transaction
- [ ] List updates after operations
- [ ] Basic error handling works

### Labels
- feature
- beginner-friendly
- frontend
- backend

### Priority
High

### Estimated Time
1-2 days

**Comment by Grace-Rasaily780** [comment]
@Munashe-Njanji,
I really appreciate your feedback and the really detailed issue raised. I will definitely work on it and make it implementable asap. Really appreciate the feature.

If you want to resolve the issue too you can create a pull request too. Please inform me about it before creating a pull request so that our code doesn't get conflicted.

Thank you,
A wannabe,
Grace Rasaily
